### ISSUE TITLE
Add testing

### ISSUE THREAD

**Issue by Kqzz** [MCGoSnipe/GoSnipe#2]
Instead of commenting / un-commenting a line to test that something works use something like [this](https://golang.org/pkg/testing/) to test if the code functions. 

Use of commenting / un-commenting: [here](https://github.com/MCGoSnipe/GoSnipe/blob/106b9db55466858b08c2e34bafb4f3a1e29ad94c/inputoutput.go#L76)

**Comment by overestimate** [comment]
I know LOL, too lazy ATM. Let me write the main methods and stuff first.

**Comment by Kqzz** [comment]
:+1:
